---
- hosts: masters:nodes
  vars:
    device: /dev/vdb
    docker_vg: docker-vg

  tasks:
  - name: check for docker storage
    shell: vgs | grep -q "{{docker_vg}}"
    failed_when: False
    changed_when: False
    register: docker_storage_test

  - name: nuke docker storage
    command: dd if=/dev/zero of="{{device}}" bs=1M count=5
    when: docker_storage_test.rc == 0
