---

- hosts: all
  name: Distribute ssh key
  gather_facts: False
  vars:
    pubkey: /root/.ssh/id_rsa.pub
  tasks:
    - name: distribute key
      authorized_key: 
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', pubkey) }}"

#- hosts: all
#  name: Configure ssh
#  gather_facts: False
#  become: True
#  tasks:
#    - name: Disable password authentication
#      lineinfile: 
#        dest: /etc/ssh/sshd_config
#        regexp: "^PasswordAuthentication"
#        line: "PasswordAuthentication no"
#        state: present
#      notify: Restart ssh
#  
#  handlers:
#   - name: Restart ssh
#     service: 
#       name: sshd 
#       state: restarted
    


