- hosts: all
  become: True
  name: Configure DNS if needed
  gather_facts: False
  roles:
    - configure_lab_dns

- hosts: all
  become: True
  name: apply common role
  gather_facts: False
  roles:
    - common_prep

- hosts: masters,nodes
  name: configure ephemeral container storage
  roles:
    - docker_storage

- hosts: all
  name: configure chrony
  vars:
    chrony_server: 'idm01.lab.moogle.cloud prefer iburst'
  roles:
     - { role: influxdata.chrony }


