- hosts: all
  become: True
  gather_facts: False
  roles:
    - common_prep

- hosts: masters
  become: True
  gather_facts: False
  roles:
    - master_prep

- hosts: nodes
  become: True
  gather_facts: False
  roles:
    - node_prep
