version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    tls:
      certificate: /etc/certs/registry.example.com.crt
      key: /etc/certs/registry.example.com.key

