---
# tasks file for master_prep
- name: create /etc/origin/master
  file:
    state: directory
    path: /etc/origin/master
  when: idmserver is defined

- name: copy CA certificate from IdM server
  get_url:
    url: https://{{idmserver}}/ipa/config/ca.crt
    dest: /etc/origin/ipa.crt
  when: idmserver is defined


