---
# tasks file for master_prep
- name: create /etc/origin/master
  file:
    state: directory
    path: /etc/origin/master
  when: idmserver is defined

- name: copy CA certificate from IdM server
  get_url:
    url: https://{{idmserver}}/ipa/config/ca.crt
    dest: /etc/origin/ipa.crt
  when: idmserver is defined


- name: Check for ca-chain.ppem
  local_action: stat path=/root/ca-chain.pem
  register: ca_chain_file

- name: Copy CA chain certificate
  copy:
    src: /root/ca-chain.pem
    dest: /etc/origin/master/ca-chain.oem
  when: ca_chain_file.stat.exists


