---
# tasks file for master_prep
- name: create /etc/origin/master
  file:
    state: directory
    path: /etc/origin/master

- name: Check if CA cert is present
  local_action: stat path=/root/ca.crt
  register: ca_file

- name: Copy CA certificate
  copy:
    src: /root/ca.crt
    dest: /etc/origin/ipa.crt
  when: ca_file.stat.exists

- name: Check for ca-chain.ppem
  local_action: stat path=/root/ca-chain.pem
  register: ca_chain_file

- name: Copy CA chain certificate
  copy:
    src: /root/ca-chain.pem
    dest: /etc/origin/master/ca-chain.oem
  when: ca_chain_file.stat.exists


