---
# defaults file for common_prep
local_repos: False
timezone: Europe/Stockholm
common_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-3.10-rpms
  - rhel-7-server-ansible-2.4-rpms
  - rhel-7-fast-datapath-rpms
repo_server: rpm.example.com
