---
# tasks file for common_prep
- name: deploy repo file
  command: curl http://192.168.122.247/pub/ose3.repo -o /etc/yum.repos.d/ose3.repo
  args:  
    creates: /etc/yum.repos.d/ose3.repo
  when: local_repos

- name: Update all packages
  serial: 2
  yum: name=* state=latest

