---
# tasks file for common_prep
#- name: deploy repo file
#  command: curl http://192.168.122.247/pub/ose3.repo -o /etc/yum.repos.d/ose3.repo
#  args:
#    creates: /etc/yum.repos.d/ose3.repo
#  when: local_repos

- name: enable repositories
  yum_repository:
    name: "local-{{ item }}"
    baseurl: "http://{{ repo_server }}/repos/{{ item }}"
    enabled: true
    description: "{{ item }}"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  with_items:
    - "{{ common_repos }}"
  when: local_repos

- name: Update all packages
  yum: name=* state=latest update_cache=true

- name: set time zone
  timezone:
    name: "{{ timezone }}"

