- hosts: localhost
  tasks:
    - name: check for kerberos credentials
      command: klist
      register: kerberos

    - fail:
        msg: "You don't have a valid kerberos ticket. Use kinit."
      when: kerberos.rc != 0

- hosts: all
  name: install ipa-client
  tasks:
    - name: install packages
      yum:
        name: ipa-client
        state: installed


- hosts: all
  serial: 1
  name: enroll to ipa server
  vars:
    otp_password: Secret123
  tasks:
    - name: check if enrolled
      command: ipa host-find {{ ansible_fqdn }}
      ignore_errors: true
      register: enrolled
      delegate_to: localhost

    - name: pre-register host
      command: ipa host-add --password {{ otp_password }} --force {{ ansible_fqdn }}
      delegate_to: localhost
      when: enrolled.rc != 0

    - name: enroll server
      command: ipa-client-install -w {{ otp_password }} -U
      when: enrolled.rc != 0
